Import('*')

_env = env.Clone()
print "AAAAAAAAAAAAAAAAAAAAA", type(_env['CPPFLAGS'])
_env.Append(CPPPATH = ['#.', '#webrtc'])
_env.Append(LIBPATH = 'lib')
_env['LIBS'] = ['c', 'rt', 'dl']

totalSources = '''
    webrtc_vad.c \
    vad_core.c \
    vad_filterbank.c \
    vad_gmm.c \
    vad_sp.c
'''

skipSources = ''



_myName='libgsv_vad'

objs = totalSources.split()


target = _env.StaticLibrary(_myName + '.a', objs, _LIBFLAGS=' -Wl,-Bsymbolic')
objs.append(target)



Return('target')
