Import('*')

_env = env.Clone()

_env.Append(CPPPATH = ['#.','#webrtc',
        '#webrtc/modules/audio_coding/codecs/pcm16b/include'])

_env.Append(LIBPATH = 'lib')
_env['LIBS'] = ['c', 'rt', 'dl']

totalSources = '''
	 pcm16b.c
'''

skipSources = '''
 
'''


_myName='libgsv_pcm16b'
objs = totalSources.split()
target = _env.StaticLibrary(_myName + '.a', objs, _LIBFLAGS=' -Wl,-Bsymbolic')
objs.append(target)

Return('target')
