Import('*')

_env = env.Clone()


_env.Append(CPPPATH = ['#.','#webrtc', 
        '#webrtc/modules/audio_coding/codecs/g711/include'])

_env.Append(LIBPATH = 'lib')
_env['LIBS'] = ['c', 'rt', 'dl']

totalSources = '''
    g711_interface.c \
    g711.c
'''

skipSources = '''
 
'''



_myName='libgsv_g711'

objs = totalSources.split()
target = _env.StaticLibrary(_myName + '.a', objs, _LIBFLAGS=' -Wl,-Bsymbolic')
objs.append(target)

Return('target')
