Import('*')

_env = env.Clone()


_env.Append(CPPPATH = ['#.','#webrtc', 
        '#webrtc/modules/audio_coding/codecs/g722/include'])

_env.Append(LIBPATH = 'lib')
_env['LIBS'] = ['c', 'rt', 'dl']

totalSources = '''
    g722_interface.c \
    g722_encode.c \
    g722_decode.c
'''

skipSources = '''
 
'''


_env.Append(CPPFLAGS = '-DG729_ARM=0')
_myName='libgsv_g722'
objs = totalSources.split()
target = _env.StaticLibrary(_myName + '.a', objs, _LIBFLAGS=' -Wl,-Bsymbolic')
objs.append(target)

Return('target')
