Import('*')

_env = env.Clone()


_env.Append(CPPPATH = ['#.', '#webrtc',
        '#webrtc/modules/audio_coding/codecs/opus/include'])

_env.Append(LIBPATH = 'lib')
_env['LIBS'] = ['c', 'rt', 'dl']

totalSources = '''
    opus_interface.c
'''

skipSources = '''
 
'''



_myName='libgsv_opus'

objs = totalSources.split()
target = _env.StaticLibrary(_myName + '.a', objs, _LIBFLAGS=' -Wl,-Bsymbolic')
objs.append(target)

Return('target')
