Import('*')
_env = env.Clone()

_env.Append(CPPPATH = ['#.','#webrtc',
        '#webrtc/modules/audio_coding/codecs/pcm16b/include'])

_env.Append(LIBPATH = 'lib')
_env['LIBS'] = ['c', 'rt', 'dl']

totalSources =[
        'audio_decoder_pcm16b.cc',
        'audio_decoder_pcm16b.h',
        'audio_encoder_pcm16b.cc',
        'audio_encoder_pcm16b.h',
        'pcm16b.c',
        'pcm16b.h',
]

skipSources = '''
 
'''


_myName='libgsv_pcm16b'
objs = totalSources
target = _env.StaticLibrary(_myName + '.a', objs, _LIBFLAGS=' -Wl,-Bsymbolic')
objs.append(target)

Return('target')
print 'AAAAAAAAAA'
