Import('*')

_env = env.Clone()

_env.Append(LIBPATH = 'lib')
_env['LIBS'] = ['c', 'rt', 'dl']

totalSources = '''
	src/g726.c \
        src/bitstream.c
'''

skipSources = '''
 
'''



_myName='libgsv_g726'

objs = totalSources.split()
target = _env.StaticLibrary(_myName + '.a', objs, _LIBFLAGS=' -Wl,-Bsymbolic')
objs.append(target)


Return('target')
