Import('*')

_env = env.Clone()


_env.Append(CPPPATH = ['#.','#webrtc', 
        '#webrtc/modules/audio_coding/codecs/g711/include'])

_env.Append(LIBPATH = 'lib')
_env['LIBS'] = ['c', 'rt', 'dl']

totalSources =[
        'audio_decoder_pcm.cc',
        'audio_decoder_pcm.h',
        'audio_encoder_pcm.cc',
        'audio_encoder_pcm.h',
        'g711_interface.c',
        'g711_interface.h',
        'g711.c',
        'g711.h',
]

skipSources = '''
 
'''



_myName='libgsv_g711'

objs = totalSources
target = _env.StaticLibrary(_myName + '.a', objs, _LIBFLAGS=' -Wl,-Bsymbolic')
objs.append(target)

Return('target')
