Import('*')

_env = env.Clone()
_env.Append(CPPFLAGS = ' ')
_env.Append(CPPFLAGS = "")
_env.Append(CPPPATH = ['#.','#webrtc',
        '#webrtc/common_audio/signal_processing/include',
        '#webrtc/modules/audio_coding/codecs/isac/main/include'])

totalSources = '''\
    arith_routines.c \
    arith_routines_hist.c \
    arith_routines_logist.c \
    bandwidth_estimator.c \
    crc.c \
    decode.c \
    decode_bwe.c \
    encode.c \
    encode_lpc_swb.c \
    entropy_coding.c \
    fft.c \
    filter_functions.c \
    filterbank_tables.c \
    intialize.c \
    isac.c \
    filterbanks.c \
    pitch_lag_tables.c \
    lattice.c \
    lpc_gain_swb_tables.c \
    lpc_analysis.c \
    lpc_shape_swb12_tables.c \
    lpc_shape_swb16_tables.c \
    lpc_tables.c \
    pitch_estimator.c \
    pitch_filter.c \
    pitch_gain_tables.c \
    spectrum_ar_model_tables.c \
    transform.c
'''

skipSources = '''
 
'''


_myName='libgsv_isac'
objs = totalSources.split()
target = _env.StaticLibrary(_myName + '.a', objs, _LIBFLAGS=' -Wl,-Bsymbolic')
objs.append(target)

################################################################################
'''
_env.Append(LIBPATH = 'lib')
_env['LIBS'] = ['c', 'rt', 'dl','sv_ilbc','sv_spl','sv_spl_neon','utils']

_myName='webrtc_ilbc_test'
totalSources = test/iLBC_test.c



objs = totalSources.split()
target = _env.Program(_myName, objs)
objs.append(target)

_myName='webrtc_ilbc_testLib'
totalSources = test/iLBC_testLib.c



objs = totalSources.split()
target = _env.Program(_myName, objs)
objs.append(target)
'''
################################################################################




Return('target')
