Import('*')

_env = env.Clone()
_env.Append(CPPFLAGS = ' ')

_env.Append(CPPPATH = ['#.', '#webrtc', './'])
_env.Append(LIBPATH = 'lib')
_env['LIBS'] = ['vpx', 'c', 'rt', 'dl']

totalSources = [
        'audio_decoder.cc',
        'audio_decoder.h',
        'audio_encoder.cc',
        'audio_encoder.h',
  ]



_myName='libgsv_modules_codecs_intf'
objs = totalSources
target = _env.StaticLibrary(_myName + '.a', objs, _LIBFLAGS=' -Wl,-Bsymbolic')
objs.append(target)


Return('target')
